# Generated by Django 3.2 on 2021-04-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField()),
                ('telfon', models.CharField(max_length=9)),
                ('yonalish', models.CharField(max_length=250)),
                ('grant', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField()),
                ('telfon', models.CharField(max_length=9)),
                ('fan', models.CharField(max_length=20)),
                ('rasm', models.ImageField(upload_to='teachers')),
            ],
            options={
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveIntegerField()),
                ('parta_soni', models.PositiveIntegerField()),
                ('stul_soni', models.PositiveIntegerField()),
                ('egasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xonalar', to='blog.teacher')),
            ],
            options={
                'verbose_name_plural': 'Xonalar',
            },
        ),
    ]
